# Breadth-First-Search and Queue Data Structure

After learning how to represent the graph in programming languages, the next natural thing is to learn how to ***travel*** into these graphs. 

Travelling inside the graph is important because it helps to address questions like :

- can we go from vertex **u** to vertex **v** (i.e is v **reachable** from u)? If yes what will be the **path**? Is this path **shortest**? Is this path **shortest** as well as **efficient** -- i.e *the best*?

- are there any *regions* inside the graph which are **disconnected** from other regions? or whole graph is **connected**?

- are there any **cyclic paths** (or **walk**) in the graphs? if yes, are cycles **simple** or **complex**?

... and many more.

One cannot answer these questions without **travelling** into the graphs. So we need to develop some ways to travel inside these graphs.

Two popular ways (or *graph traversal algorithms*) are :

- **Breadth-First Search (BFS)**
- **Depth-First Search (DFS)**

The choice between BFS and DFS depends upon the specific requirements and nature of the problem we are solving. 

In this lecture we will discuss the BFS and in next lecture the DFS will be discussed.

## BFS

The Breadth First Search (BFS) algorithm is used to traverse a graph or a tree in a *breadth-first manner*.

- BFS starts at the *root node* and explores all the *neighboring nodes* at the **current depth** or **level** before moving on to the nodes at the **next depth**.

- This is done by using a **queue** data structure. 

- The algorithm marks each visited node to avoid revisiting it.

[source: https://pdsaiitm.github.io/week-4/summary.html]

Without the **Queue** data structure we cannot implement or code the BFS technique.So lets develop the **Queue** data structure first.

## The Queue Datastructure.

**Queue** is the sequence in which *the member who entered first will be the first one to get out* --> **F**irst-**I**n-**F**irs-**O**ut or (**FIFO**). This type of Datastructure is very much needed for the techniques like BFS to function. 

*Queue* style datastructure is not prebuilt inside *standard python*, but Python provides '**Class**' facility to built any required datastructure in our own customized way.

Things we want to do with a sequence called **queue** are:

- *Adding* a member at the end of the sequence --> **enqueue** facility.

- *Removing* a member from the beginning of the sequence --> **dequeue** facility.

- *Checking whether the sequence is empty or not* --> **is_empty** facility.

- *checking the next element to be out without actually removing it* --> **head** or **peek** facility.

- *checking the last element to be out without actually removing it* --> **tail** facilty.

- *checking the length* of the sequence. --> **size** facility.

- *getting a view of whole sequence* --> **print** facility.

Lets now design this datastructure in python.

In [2]:
class Queue:

    def __init__(self):
        self.queue=[]
    
    def is_empty(self):
        if (len(self.queue)==0):
            return True
        else:
            return False
    
    def enqueue(self,item):
        self.queue.append(item)
    
    def dequeue(self):
        if(self.is_empty()==False): # other way to write it "if (not self.isempty())"
            head=self.queue[0]
            self.queue=self.queue[1:] 
            # above two steps can be done in a single step by just "self.queue.pop(0)"
            # .pop(i) is a function present in standard python library to remove and return the items
            # at i th index from the mutable sequence types and doing an side-effect on the sequence too.
            # if .pop() is used without index it will take out the last item.
            return head
        else:
            return None
            # when there is nothing to return in the else statement, python allows to 
            # simply drop this else block as python itself handel the situation by implicitly returning 'None'.
       

    def head(self):
        if (self.is_empty()==False):
            return self.queue[0]
        else:
            return None
    
    def tail(self):
        if (self.is_empty()==False):
            return (self.queue[len(self.queue)-1])
        
    def size(self):
        return len(self.queue)
    
    def __str__(self):
        return (str(self.queue))
    
        # the __str__ function dictates the output of the 'print' function for the class instances. 
    

Here we have a customized **queue** datastructure with all the facilities added to it.

Lets now use it.

In [3]:
q=Queue()   # make an instance of the queue class.

for i in range(4):
    q.enqueue(i) # enqueue function will accept a data
    print(q) # __str__ function in Queue class dictate this output.

print(q.is_empty())
print(q.head())
print(q.tail())
print(q.size())

for i in range(q.size()):
    q.dequeue()
    print(q)

print(q.is_empty())
print(q.head())
print(q.tail())
print(q.size())

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
False
0
3
4
[1, 2, 3]
[2, 3]
[3]
[]
True
None
None
0


Once we have the **queue** Data structure in place we can proceed to perform BFS techinque on graph.

## BFS technique implementation 

Suppose we have a graph :

V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)] 

and we want to know -->  what all are the places(vertices) which I can *reach* if I starts from vertex **0**.

First lets build the graph in workable form - *Adjecency Matrix* or *Adjecency list*.

In [1]:
#Building the graph

# Graph represented as collection of vertices and Edges G(V,E) :
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

# We cannot work with this representation programatically so we need to convert it into workable form.

# Defining Adjcency matrix builder function

import numpy as np

def adjecencyMatrix(vertices,edges):

    #initialize the zero matrix of vertices
    (rows,cols)=(len(vertices),len(vertices))
    mat=np.zeros((rows,cols),dtype=int)

    #populating zeromatrix with edges
    for (i,j) in edges:
        mat[i][j]=1

    return mat


# Defining Adjecency List builder function 

def adjecencyList(vertices, edges):

    #creating the empty dictionary of vertices
    aListDic={}
    for i in vertices :
        aListDic[i]=[]

    # populating the dictionary with list of neighbours (using edges).
    for (k,j) in edges:
        aListDic[k].append(j)
        aListDic[k].sort() # this do the in-place sorting of the list 
    
    return aListDic


# Now building the Adjecency Matrix and Adjecency List        
aMat=adjecencyMatrix(V,E) # Adjececncy Matrix
aList=adjecencyList(V,E) # Adjecency List.


print(f"Adjecency Matrix : \n{aMat}\n")
print(f"Adjecency List: \n{aList}\n")



# In this way our Graphs are ready to travel now. We can use either of Adjecency Matrix or Adjecency list acc to Need.

Adjecency Matrix : 
[[0 1 1 0 0]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]

Adjecency List: 
{0: [1, 2], 1: [3, 4], 2: [3, 4], 3: [4], 4: []}



Now we have a *workable* graph in place. In which we can travel *programatically*.

We want to begin or journey from vertex **0** (so it is our **root vertex**) and see till which extent I can reach from here inside the given graph.


**BFS**

As we know in *Breadth-First* style we explore all the vertices level by level and do not proceed to the next level without finished exploring all the vertices in the current level. Also we should not travel the vertex (or path) twice.

We plan the BFS in following way:

1. Go to the vertex **0** and mark it *visited*. (For this maintain a *visited* dictionary).
2. Put zero inside a *queue* called --***to be explored queue***, so that it is scheduled for *exploration* very first time as we process the queue.( by *exploring* a vertex we mean 'visiting' all its *neighbouring vertices* and marking it 'visited').

3. Now dequeue the **0** out of the "**to be explored queue**", and start *exploring* it('visit' all its *neighbours*).

    During *exploration* of the vertex **0**, we 'visit' its neigbouring vertices one-by-one and mark them 'visited'.Simultaniously they are enqueued inside the "*to be explored queue*" for scheduling their exploration later. Notice that by enqueing the neighbours of **0**, 'ahead' inside the queue, it is ensured that they are scheduled to be explored before the neighbours of any other vertices. This is in-line with the philosophy of BFS where we have to first explore all the vertices of current level then proceed to next level.
    
    **Note** - *The queue Datastructure will ensure that the first vertices to be explored will be the neighbours of *root vertex*, **0** in this case.*


    If during exploration of **0** we visit any vertex that is already *visited* we must not enqueue it again into the queue for later exploration. As all the visited marked vertices are already enqueued for exploration (at the time when they were marked visited). By this we ensures that any vertex in the graph is not explored more than one time.

4. Once the exploration of **0** is complete we will take out another visited vertex from the "**to be explored queue**", explore it, and mark its unvisited neighbours 'visited' and enque them for later exploratior.

... repeat this step untill the whole queue becomes empty.

5. At the end, when '**to be explored queue**' becomes empty,we will return the **visited** Dictionary which stores the information about which vertices are set to **True** and which remains **unreachable**.

Lets code this strategy now.

First we will try to do BFS on the ***Adjecency Matrix representation*** of Graph, then we will do it on ***Adjecency List representation*** of the same graph. Then we will analyse which is the better approach. 

### BFS on Adjecency Matrix of the Graph

In [5]:
# BFS with Adjecency Matrix

# We aready initiated a Queue Datastructure and Adjecency Matrix and List representations of graph
# these are prerquisite for the BFS

'''
First define a function which will find the list of neighbours of given vertex from Adjecency matrix.
This will be needed in *exploring* act of a vertex during BFS. 
'''
import numpy as np
# defining a nighbour function 
def neighbours(adjMat,v):
    rows,cols=np.shape(adjMat)
    nList=[]
    for j in range(cols):
        if adjMat[v][j]==1:
            nList.append(j)
    
    return nList
    
# now define BFS
    
def BFS_adjMat(adjmatrix,startVertex):

    visited={} # a dictionary to keep record of visited vertices
    exploreQ=Queue() # a 'to be explored queue' to keep ordered sequence of vertices to be explored
    (rows, cols)=np.shape(adjmatrix) # get the shape of adjecency matrix to have an idea of there are how many vertices in the graph 
    
    # Now initializing the visited dictionary

    for i in range(rows):
        visited[i]=False


    #Mark the start vertex as visited and enqueue it inside 'to be explored queue', so that it is listed for exploring
    visited[startVertex]=True
    exploreQ.enqueue(startVertex)

    # start exploring from the visited vertex by dequing it from the queue

    while(exploreQ.is_empty()==False):

        e=exploreQ.dequeue() # take out the vertex to explore
        print(f"vertex to be explored : {e}")
        print(f"Neigh. of {e} : {neighbours(adjmatrix,e)}")
        # now explore
        for k in neighbours(adjmatrix,e):
            if (visited[k]==False):
                visited[k]=True # set the unvisited vertex to be 'visited'
                print(f"updated visited : {visited}")
                exploreQ.enqueue(k) # enqueue it for late exploration 
                print(f"current status of q : {exploreQ}")


    return visited


print(BFS_adjMat(aMat,0))


vertex to be explored : 0
Neigh. of 0 : [1, 2]
updated visited : {0: True, 1: True, 2: False, 3: False, 4: False}
current status of q : [1]
updated visited : {0: True, 1: True, 2: True, 3: False, 4: False}
current status of q : [1, 2]
vertex to be explored : 1
Neigh. of 1 : [3, 4]
updated visited : {0: True, 1: True, 2: True, 3: True, 4: False}
current status of q : [2, 3]
updated visited : {0: True, 1: True, 2: True, 3: True, 4: True}
current status of q : [2, 3, 4]
vertex to be explored : 2
Neigh. of 2 : [3, 4]
vertex to be explored : 3
Neigh. of 3 : [4]
vertex to be explored : 4
Neigh. of 4 : []
{0: True, 1: True, 2: True, 3: True, 4: True}


This was the BFS on the **Adjecency Matrix representation**, lets now quickly do the BFS on **Adjecency List representation**.

In [11]:
# BFS on Adjecency List representation of the graph.

# we already prepared the Adjecency List of the graph and stored in aList variable.

def BFS_adjList(adjList,startVertex):

    #initialize the visited dictionary
    visited={}
    
    for i in adjList.keys():
        visited[i]=False
    
    #initialize 'toExploreQ'
    
    toExploreQ=Queue()

    # Visit the starting vertex and enque it for exploration 
        
    visited[startVertex]=True
    toExploreQ.enqueue(startVertex)

    # start exploring the visited vertex from queue

    while (toExploreQ.is_empty()==False):

        e=toExploreQ.dequeue() # take out the vertex to be explored

        # now explore
        for k in adjList[e]:
            if(visited[k]==False):
                visited[k]=True # set the unvisited vertex 'Visited'
                toExploreQ.enqueue(k)  # enqueue it for later exploration.
    
    return visited  


print(BFS_adjList(aList,0))

{0: True, 1: True, 2: True, 3: True, 4: True}


Notice that the only difference which occurs into the adjecency List is that here we dont need an extra function **neighbours** to look for the neigbours of each vertex. Infact the list of neighbours are itself maintained in the Adjecency list representation. This advantage saves computations resource for us and code works more efficiently. We will soon see this advantage during analysis of complexities of BFS with adjecency matrix and Adjecency list.


## Complexity Analysis of BFS

Now the question is - with which representation of graph among **Adjecency List** or **Adjecency matrix**, BFS is more efficient?

Let the Graph have $n$ vertices and $m$ edges. Now:

**With Adjecency Matrix** :

- $n$ steps to initialize the **visited** dictionary. 
- $n$ steps to *explore* or look at the neighbours of each vertex.

    - this was done by the neighbour function which look through all the columns of the specific row to which vertex belongs in Adjecency Matrix to extract the List of neighbours.Notice even if only one neighbour is present for a vertex the neighbour function have to take $n$ steps and look through all the columns to prepare the list of neigbours for that vertex.

- So overall time is $O(n^2)$ i.e --> Quadratic complexity.

**With Adjecency List** :

- $n$ steps to initialize the **visited** dictionary.
- $2m$ i.e sum of degrees of all the vertices (m = no of edges), steps to in total to explore all the vertices.

    - Notice that in **Adjecency List** representation we dont have any **neighbour** function to extract the list of neighbours, infact the neighbour list of each vertex is already present in adjecency list. For some vertex there are few neighbours (degree of a vertex), and for some others there could be more neighbours thus during execution we specifically dont know exactly how much time it takes to process a single vertex --> but for all vertex we know for sure that the total time taken will be sum of their individual degree (i.e 2 times the number of edges present in the Graph).

    - Why '2 times' the number of edges?

    Because each edge $(i,j)$ in undirected graph contributes to the degree of vertex $i$ and and also to the degree of vertex $j$. So one edge contributes 2 degrees 

    **NOTE** - This style of Analysis is called the **amortized analysis**, in which we are not interested on individual details of each process but we will consider and look the process as a 'whole'. --**Amortized Analysis**

- So over all time is $O(n+2m)$ ---> we can put off the 2 and finally --->  $O(n+m)$ i.e --> Linear  Complexity!.


Most graphs that we deal with in real life have much smaller number of edges than the square of the number of vertices. i.e ($m<<n^2$). 

In what we call a **sparse graph** is the one in which number of edges are proportinal to $n$ rather than $n^2$. 

Thus the complexity $O(m+n)$ is much better than complexity $n^2$. Thus **Adjecency List** representation is better than  **Adjecency Matrix** in case of BFS.

**Note**- It turns out that in graph we cannot do better than the complexity $O(m+n)$ because to do any analysis we atleast have to look whole graph ($m+n$).


This was all for part1 of lecture 3 now we will enhance the BFS to record path also. 