# Different ways of representing graphs in Python.

A **graph** is a collection of two things --- **Vertices** and the *relation* between them -- **Edges**

We are given a graph **G(V,E)**. 

Where V -> list of vertices and E -> list of Edges.

Let V = [0,1,2,3,4]

It is convenient and preferred to represent the vertices using **numbers** because it then become easy to represent the graph in programming languages.  (Technically it is allowed that vertices can be characters or strings. But with non integers the graphs are tricky and challenging  to implement and then work with in programming languages)

E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)] 

Notice a single edge is represented by a tuple (i,j) which means there is an edge **from** vertex i **to** vertex j.

Our task is to represent this graph in python in different ways. 

There are two popular ways of representing the graphs in programming languages - **Adjecency Matrix** and **Adjecency List**.

- Adjecency matrix can be created
    - using *python lists* or.
    - using *numpy 2-D arrays* data structures.

- Adjecency list can be created
    - using *python lists* or.
    - using *python Dictionaries* data structures.


## Adjecency Matrix Representaion 

A matrix is implimented in programming language as 'List' of 'lists'. Or collection of rows.

### Creating Adjecency Matrix Using Python List 

If we are given the V and E, the Adjecency Matrix of graph can be implemented using normal python lists as follows:


In [19]:
# Adjecency matrix representation of graph G(V,E) using python lists.
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]
def aMat1(V,E):
    (rows,cols) = (len(V),len(V))
    mat=[]
    # initializing the zero matrix
    for i in range(rows):
        mat.append([])
        for j in range(cols):
            mat[i].append(0)
    # polpulating the zero matrix with edges
    for i,j in E:
        mat[i][j]=1

    return mat 

G=aMat1(V,E)
print(G)
print(type(G))
      


[[0, 1, 1, 0, 0], [0, 0, 0, 1, 1], [0, 0, 0, 1, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0]]
<class 'list'>


### Creating Adjecency Matrix Using Numpy 2D array.

List representation of matrix have some disadvantages in terms of providing the *random access* to its entries.
Thus it is preferred to use the **Numpy arrays** to construct the the Adjecency matrix of graph. This representaion provides **random access** to the entries inside it.

**numpy module** provides the facility to create the Matrix directly without loops and that too in different ways, two of them are :

- using **numpy.array()** (with *list comprehension*).
- using **numpy.zeros()** (prefered)


In [18]:
#Adjecency matrix representation of Graph(V,E) using numpy 2D array

# method 1 using numpy.array with list comprehension :

import numpy as np
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def aMat2(V,E):
    (rows,cols)=(len(V),len(V))

    mat=np.array([[0 for j in range(cols)] for i in range(rows)]) # Notice how zero matrix is initialized in single line using list comprehension.

    #Now populating the matrix with edges

    for i,j in E:
        mat[i][j]=1
    
    return mat

G=aMat2(V,E)
print(G)
print(type(G))

[[0 1 1 0 0]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
<class 'numpy.ndarray'>


In [23]:
#method -2 using numpy.zeros 
# numpy already imported
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def aMat3(V,E):
    (rows,cols)=(len(V),len(V))

    # initializing zero matrix
    mat=np.zeros((rows,cols),dtype=int) # Notice we didnt even used the list comprehension here.
    # if we skip the 'dtype=int' part we get the floating point zeros like "0.", try to remove it and see
     
    #Now populating the matrix with edges

    for (i,j) in E:
        mat[i][j]=1
    
    return mat

G=aMat3(V,E)
print(G)
print(type(G))

[[0 1 1 0 0]
 [0 0 0 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]
 [0 0 0 0 0]]
<class 'numpy.ndarray'>


## Adjecency list representaion 

Sometime if a Graph have more vertices and comparitively lesser edges then the Adjecency Matrix representaion is not the best way to represent the Graph as it contains lots or unnecesary 0s which we are not much interested in.(There are other reasons also)

In such case we should try to represent the graphs using **adjecency list**.

Adjecency list contains list of the neighbours (to which a given vertex is directly connected by an edge) for every vertex. This can be implemented in python two ways -

- using 'list' of 'lists'.
- using Python Dictionaries. (prefered)

### Creating Adjecency List Using list of list

We can make this list of list using **python lists** or **numpy arrays**.

Lets do it with Normal python list:


In [29]:
# Adjecency List using python List.
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def adjList1(V,E):
    adjList=[[j for (k,j) in E if k==i ] for i in V]
    return adjList

G=adjList1(V,E)
print(G)
print(type(G))

[[1, 2], [3, 4], [4, 3], [4], []]
<class 'list'>


Here the *index* of outer array represent the *vertex* and values coresponding to it represents the list of its neighbouring vertex.

In [30]:
# Adjecency list using Numpy arrays
# numpy already imported

V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def adjList2(V,E):
    (rows,cols)=(len(V),len(E))

    adjList=np.array([[j for (k,j) in E if k==i] for i in V])
    return adjList

G=adjList2(V,E)
print(G)
print(type(G))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

Notice that above code is giving an Value error. It complains that the ***numpy array cannot store the arrays of different list sizes***. Numpy arrays can hold the lists if they were of *equal sizes*.

But one can override and run off from this error if we convert the unequal sizes arrays to "`object`" datatype as follows.

In [31]:
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def adjList2(V,E):
    (rows,cols)=(len(V),len(E))

    adjList=np.array([[j for (k,j) in E if k==i] for i in V], dtype=object)
    return adjList

G=adjList2(V,E)
print(G)
print(type(G))

[list([1, 2]) list([3, 4]) list([4, 3]) list([4]) list([])]
<class 'numpy.ndarray'>


Look now the error has gone. We still have an numpy array , but its an array of '`objects`' not of numbers. 

This is generally not preffered.

**[Windows copilot]**

Using `dtype=object` in NumPy arrays is not generally preferred for numerical computations because it can lead to performance issues and unexpected behavior, especially with operations that are optimized for numerical data types like float or int. Arrays with dtype=object are essentially arrays of pointers to Python objects, which means they don’t benefit from NumPy’s optimizations for numerical operations.

However, `dtype=object` can be useful when you need to store a collection of arbitrary Python objects, such as a mix of different data types that can’t be accommodated by a single numerical dtype. It allows for flexibility, but with the trade-off of performance and some functionality that is available with homogeneous numerical arrays.

### Creating Adjecency List Using Python Dictionaries.

It is the most prefered way to represent graphs in terms of Adjecency list.

In [33]:
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def adjList3(V,E):
    (rows,cols)=(len(V),len(V))
    adjList={}
    # initializing the vertices inside the dictionary
    for v in V:
        adjList[v]=np.array([])
        
    # populating vertices with neigbouring vertices
        
    for (i,j) in E:
        adjList[i].append(j)
    
    return adjList

G=adjList3(V,E)
print(G)
print(type(G))





AttributeError: 'numpy.ndarray' object has no attribute 'append'

Notice The error AttributeError: 'numpy.ndarray' object has no attribute 'append' occurs because NumPy arrays do not have an append method. The append method is a feature of Python’s list data structure, not NumPy arrays. When you attempt to use append on a NumPy array, Python cannot find this method, hence the error.

To fix this, you can either use a Python list instead of a NumPy array within your dictionary or use the numpy.append() function, which returns a new array with the appended value. However, remember that numpy.append() does not modify the array in place; it creates a new array each time you use it.

Sp lets use the python list to make above code run.

In [34]:
V = [0,1,2,3,4]
E = [(0, 1), (0, 2), (1, 3), (1, 4), (2, 4), (2, 3), (3, 4)]

def adjList3(V,E):
    (rows,cols)=(len(V),len(V))
    adjList={}
    # initializing the vertices inside the dictionary
    for v in V:
        adjList[v]=[]
        
    # populating vertices with neigbouring vertices
        
    for (i,j) in E:
        adjList[i].append(j)

    # sort the neighbourlist of each vertex. (it is preferred and recomended)
    for k in V:
        adjList[k].sort()  # sort() method do the 'in place' sorting and do a permanent side effect on the orignal list.
    
    return adjList

G=adjList3(V,E)
print(G)
print(type(G))

{0: [1, 2], 1: [3, 4], 2: [4, 3], 3: [4], 4: []}
<class 'dict'>
